Fix/handle incorrect yaml file
teknoir/node-red-teknoir-configure-devices pull request #3
Opened 2024-05-07 09:59 UTC by jeryini

### Overview
* Added check so that only `Deployment` kind manifest is processed in `configureDevice`
* Additional `try/catch` statements to catch if also `Deployment` kind manifest does not contain all appropriate fields
* Test coverage

2024-05-07 10:11 UTC, tekn0ir approved these changes

2024-05-07 10:20 UTC, tekn0ir requested changes

2024-05-07 10:20 UTC, tekn0ir commented on debug/package.json
>    },
Update version of the module in the package and you can hopefully test a hot rollout!

2024-05-13 12:53 UTC, tekn0ir approved these changes

2024-05-13 13:03 UTC, merged

2024-05-14 10:54 UTC, jeryini commented
Update tested here: https://teknoir.cloud/_/devstudio/surveillance-24hrsnetwork/configure-devices-test/?ns=prime-communications#flow/1fb197b84dab3093