[PRO-2330] Better error handling
teknoir/node-red-teknoir-configure-devices pull request #4
Opened 2024-08-02 15:52 UTC by vovateknoir

* Checks for data integrity
* Actual filtering valid data
* Added command for local debugging
* (?) Removed (seem)unnecessary dependency

2024-08-02 15:53 UTC, vovateknoir commented on package.json
> +  "files": [
AFIU these are basically what is needed for a package.

2024-08-02 15:54 UTC, vovateknoir commented on package.json
> -    "node-red-teknoir-configure-devices": "github:teknoir/node-red-teknoir-configure-devices#main"
Do we need this dependency?

2024-08-02 15:55 UTC, vovateknoir commented on src/configure-device.js
> +        newItems = newItems.filter(manifest => manifest && manifest.hasOwnProperty('kind') && manifest.kind === 'Deployment').map(manifest => {
Now items actually filtered. So, any malformed node won't be accepted.

2024-08-05 12:26 UTC, tekn0ir requested changes
Can you bump the version in the [package](https://github.com/teknoir/node-red-teknoir-configure-devices/blob/f9fac0fa11c05381a08eeafc3be61ac76e3e67e1/package.json#L3), and create a branch with the same name.

You can also bump the version in the teknoir plugin catalog: https://github.com/teknoir/devstudio-catalog/blob/cd9c3d4fb30fae201353fb1bd4f7102f63ae753d/catalogue.json#L99

And after that bump the version in the Cloud Devstudio: https://github.com/teknoir/devstudio-cloud/blob/273a88c0ea67fc27acf4456e78b7277b047af2c9/Dockerfile#L68

And after that you can test it by creating the failing Devstudio in `teknoir-retail`. Create it with the name `retail`, and use existing Volume.

2024-08-05 12:26 UTC, tekn0ir commented on package.json
> -    "node-red-teknoir-configure-devices": "github:teknoir/node-red-teknoir-configure-devices#main"
Most likely not

2024-08-08 11:23 UTC, vovateknoir commented
@tekn0ir Done

https://github.com/teknoir/devstudio-catalog/pull/8
https://github.com/teknoir/devstudio-cloud/pull/28

![image](https://github.com/user-attachments/assets/13725d14-f697-4159-9570-fcacf1bc5d64)

![image](https://github.com/user-attachments/assets/f2e5196a-b12f-4e6c-9d83-d8b1920895f8)

2024-08-29 09:55 UTC, jeryini approved these changes

2024-09-05 08:46 UTC, vovateknoir commented
Merged from another branch

2024-09-05 08:46 UTC, closed without merging